# Promise
Promise - обещание. Когда это обещание исполниться, мы можем что-либо сделать.

```
const promise = new Promise((resolve, reject) => {
  console.log("Обещание"); // -> Обещание
});

// Сработает, когда "обещание" будет выполнено
promise.then(() => {
  console.log("Обещание исполнено!"); // -> 
});
```

# Resolve
В результате выполнения этого кода, мы увидим в консоли только "Обещание", потому что `Promise` не считается успешно выполненным.
Чтобы увидеть в консоли надпись "Обещание исполнено!", нужно заменить `console.log("Обещание")` на `resolve("Обещание")`

```
const promise = new Promise((resolve, reject) => {
  resolve("Обещание");
});

promise.then(() => {
  console.log("Обещание исполнено!"); // -> 
});
```

**Пояснение**
Так происходит, потому что `.then` у `Promise` выполняется только тогда "обещание" выполнено. Мы можем указывать действия при выполнении (`resolve`) и не выполнении (`reject`) "обещания".

Если использовать следующий код, то в консоль мы получим ошибку. Так происходит потому что `Promise` выполняется не успешно, а "Обещание исполнено!" мы выводим в консоль только в случае успешного выполнения.

```
const promise = new Promise((resolve, reject) => {
	// resolve -> reject
  reject("Обещание"); // -> Обещание
});

// Сработает, когда "обещание" будет ВЫПОЛНЕНО
promise.then(() => {
  console.log("Обещание исполнено!"); // -> 
});
```

Чтобы получить заветную надпись в консоль нужно заменить `.then` на `.catch`.

# Reject
```
const promise = new Promise((resolve, reject) => {
  reject("Обещание"); // -> Обещание
});

// Сработает, когда "обещание" будет ВЫПОЛНЕНО
promise.catch(() => {
  console.log("Обещание исполнено!"); // -> 
});
```

**Итог**
Если нам нужно обработать успешное выполнение кода (`resolve`), мы используем `.then`, если наоборот, не успешное (`reject`), то используем `.catch`. Или же можно в `.then` через запятую передать еще одну функцию, которая будет выполнять код при провале "обещания", а первая при его исполнении.

Также можно использовать `resolve` по-другому:
```
const promise = new Promise((resolve, reject) => {
  console.log("Обещание"); // -> Обещание
  resolve();
});

promise.then(
	function () {
		console.log("Обещание выполнено!");
	},
	function () {
		console.log("Обещание провалено!");
	}
);
```

# Пример
Мы можем с помощью `Promise` обработать нажатие на кнопку.
```
const promise = new Promise((resolve, reject) => {
  btn1.addEventListener("click", () => {
    resolve();
  });
});

promise.then(() => {
  console.log("Обещание исполнено!");
});
```

# Передача параметров
В качестве `resolve` и `reject` мы передаем функции, которые прописаны в `.then`. Соответственно мы можем и в этих функциях принимать параметры:

```
const promise = new Promise((resolve, reject) => {
  btn1.addEventListener("click", () => {
    resolve("выполнено!");
  });
  
  btn2.addEventListener("click", () => {
    reject("провалено!");
  });
});

promise.then(
  function (text) {
    console.log("Обещание " + text);
  },

	function (text) {
    console.log("Обещание " + text);
  }
);

```

**Важно**
Один `Promise` может иметь только одно состояние (либо обещание выполнено, либо провалено).

# Promise.all()
Перепишем наш код так, чтобы появлялось окно, но только при нажатии двух кнопок.

```
const promise1 = new Promise((resolve, reject) => {
  btn1.addEventListener("click", () => {
    resolve();
  });
});

const promise2 = new Promise((resolve, reject) => {
  btn2.addEventListener("click", () => {
    resolve();
  });
});
```

И чтобы проверить состояния всех `Promise`, мы можем использовать метод `.all()`:

```
Promise.all([promise1, promise2]).then(() => {
  alert("Все обещания выполнены!");
});
```

`Promise.all()` принимает массив, который содержит все `Promise`, которые должны быть выполнены, а затем в `.then` указываем, что нужно сделать. 

Мы также можем передать и вторую функцию, которая будет отвечать за провал "обещания" по аналогии с [Reject](#Reject).

---
[[Асинхронность]]